---
env:
  browser: true
extends:
  - eslint-config-airbnb
  - ../.eslintrc.yml
rules:
  react/jsx-filename-extension: 0
  react/forbid-prop-types: 0
  react/jsx-indent: 0
  react/jsx-one-expression-per-line: 0
